version: 0.2

phases:
  pre_build:
    commands:
      
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/zinclabs
      - apt-get update  && apt-get install bc -y
      - apt-get install -y qemu-user-static
      # Install AWS CLI
      # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      # - unzip awscliv2.zip
      # - ./aws/install
      # - rm awscliv2.zip
      # - rm -rf aws

      # install buildx
      - wget -nv https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64
      - chmod +x buildx-v0.7.1.linux-amd64
      - mkdir -p ~/.docker/cli-plugins
      - mv buildx-v0.7.1.linux-amd64 ~/.docker/cli-plugins/docker-buildx


      - export DOCKER_CLI_EXPERIMENTAL=enabled
      - export DOCKER_BUILDKIT=1
  build:
    commands:
      - docker buildx create --name mybuilder --use --bootstrap
      - docker buildx build --push \
        --platform linux/amd64,linux/arm64 \
        --tag public.ecr.aws/zinclabs/debug-ubuntu-base:latest .



      

